os: osx
osx_image: xcode8
language:
- objective-c
- android
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.1
  - android-23
sudo: false
notifications:
  email: false
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- npm install -g cordova
before_script:
- cordova platform add ios
#- cordova platform add android
script:
- npm test

