os: osx
osx_image: xcode8
language: objective-c
sudo: false
notifications:
  email: false
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
- npm install -g cordova
before_script:
- cordova create tmp
- mv tmp/* .
- rmdir tmp
- cordova platform add ios
script:
- npm test

