os: osx
osx_image: xcode8
language: objective-c
sudo: false
notifications:
  email: false
before_install:
- npm install -g cordova@7.0.1
before_script:
- cordova create tmp
- mv tmp/* .
- rmdir tmp
- cordova platform add ios
script:
- npm test

